# Define a imagem Docker base para executar o pipeline
image: docker:latest

services:
  - docker:dind

# Define as fases do pipeline
stages:
  - build

# Define o trabalho que ir치 construir a imagem
build_image:
  stage: build
  variables:
    # Define a tag da imagem para o formato do Docker Hub, usando o seu nome de utilizador
    # e o nome do projeto GitLab (ex: seu_user/v8-app:latest)
    IMAGE_TAG: $DOCKERHUB_USERNAME/$CI_PROJECT_NAME:latest
  
  # Faz o login no Docker Hub usando as vari치veis de ambiente seguras
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

  # O script principal: constr칩i e envia a imagem para o Docker Hub
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  
  # Define que este trabalho s칩 executa na branch 'main'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"